# Generated by Django 5.2.12 on 2026-04-03 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('customer_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('email_domain', models.CharField(db_index=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_tenure_days', models.PositiveIntegerField()),
                ('total_orders', models.PositiveIntegerField()),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=18)),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('lifetime_value_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('customer_segment', models.CharField(db_index=True, max_length=10)),
            ],
            options={
                'db_table': 'customer_analytics',
                'ordering': ['customer_id'],
            },
        ),
        migrations.CreateModel(
            name='OrderAnalytics',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('order_hour', models.PositiveSmallIntegerField()),
                ('total_items', models.PositiveIntegerField()),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_discount_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount_ratio', models.DecimalField(decimal_places=4, max_digits=8)),
                ('order_complexity_score', models.PositiveIntegerField()),
                ('dominant_category', models.CharField(db_index=True, max_length=255)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='analytics.customeranalytics')),
            ],
            options={
                'db_table': 'order_analytics',
                'ordering': ['order_id'],
            },
        ),
    ]
